name: ETL
run-name: "ETL, repo: ${{ inputs.repository }}"

on:
  workflow_dispatch:
    inputs:
      repository:
        type: string
        description: The directory to run the ETL on. Like 'hashicorp/waypoint'
        required: false
      content-dir:
        type: string
        default: "content"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "=== SETUP ==="
      - name: Make ETL Actions Available
        uses: actions/checkout@v3
  extract:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "=== EXTRACT ==="
      - name: Run Extract Action
        uses: ./actions/extract
        with:
          milliseconds: 2000
  transform:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "=== TRANSFORM ==="
  load:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "=== LOAD ==="
