name: ETL
run-name: "ETL, repo: ${{ inputs.repository }}"

on:
  workflow_dispatch:
    inputs:
      repository:
        type: string
        description: "The directory to run the ETL on. Example: `hashicorp/waypoint`"
        default: "thiskevinwang/extract-transform-load"
        required: false
      parent-dir:
        type: string
        description: "The directory that contains `content-dir` and `data-dir`; Example: `website`"
      content-dir:
        type: string
        description: "The directory that contains the markdown files; Example: `website/content`"
      data-dir:
        type: string
        description: "The directory that contains the data files; Example: `website/data`"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "=== SETUP ==="
      - uses: actions/checkout@v3
      # Make actions available to subsequent jobs
      - uses: actions/upload-artifact@v3
        with:
          name: etl-actions
          # This uploads the ./extract, ./load, and ./transform directories
          path: actions/
          retention-days: 1

  extract:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: etl-actions
          path: actions
      - name: Checkout content repository and store it in `/repo-contents`
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repository }}
          path: repo-contents
      - name: Run Extract Action
        uses: ./actions/extract
        with:
          working-directory: ${{ github.workspace }}/repo-contents
          parent-directory: ${{ inputs.parent-dir }}
          content-directory: ${{ inputs.content-dir }}
          data-directory: ${{ inputs.data-dir }}
      # - run: |
      #     ls -R repo-contents
      - name: "Upload repo 'website' dir"
        uses: actions/upload-artifact@v3
        with:
          name: repo-contents
          path: repo-contents/${{ inputs.parent-dir }} # contents of ./website
          retention-days: 1

  transform:
    needs: extract
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: etl-actions
          path: actions
      - uses: actions/download-artifact@v3
        with:
          name: repo-contents
          path: repo-contents/${{ inputs.parent-dir }}
      - name: Run Transform Action
        uses: ./actions/transform
        with:
          working-directory: ${{ github.workspace }}/repo-contents
          parent-directory: ${{ inputs.parent-dir }}
          content-directory: ${{ inputs.content-dir }}
          data-directory: ${{ inputs.data-dir }}
      - name: "Upload repo 'website' dir, transformed"
        uses: actions/upload-artifact@v3
        with:
          name: repo-contents-transformed
          path: repo-contents/${{ inputs.parent-dir }}
          retention-days: 1

  load:
    needs: transform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: etl-actions
          path: actions
      - uses: actions/download-artifact@v3
        with:
          name: repo-contents-transformed
          path: repo-contents/${{ inputs.parent-dir }}
      - name: Run Load Action
        uses: ./actions/load
        with:
          working-directory: ${{ github.workspace }}/repo-contents
          parent-directory: ${{ inputs.parent-dir }}
          content-directory: ${{ inputs.content-dir }}
          data-directory: ${{ inputs.data-dir }}
