name: ETL
run-name: "ETL, repo: ${{ inputs.repository }}"

on:
  workflow_dispatch:
    inputs:
      repository:
        type: string
        description: The directory to run the ETL on. Like 'hashicorp/waypoint'
        required: false
      content-dir:
        type: string
        default: "content"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "=== SETUP ==="
      - uses: actions/checkout@v3
      # Make actions available to subsequent jobs
      - uses: actions/upload-artifact@v3
        with:
          name: etl-actions
          # This uploads the ./extract, ./load, and ./transform directories
          path: actions/
          retention-days: 1

  extract:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: etl-actions
          path: actions
      # # For debugging
      # - name: Display structure of downloaded files
      #   run: ls -R
      - name: Run Extract Action
        uses: ./actions/extract # This might not need to do anything...
        with:
          milliseconds: 2000
      - name: Checkout content repository and store it in `/repo`
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repository }}
          path: repo-contents
      - uses: actions/upload-artifact@v3
        with:
          name: repo-contents
          path: repo-contents
          retention-days: 1

  transform:
    needs: extract
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: etl-actions
          path: actions
      - uses: actions/download-artifact@v3
        with:
          name: repo-contents
          path: repo-contents
      - name: Run Transform Action
        uses: ./actions/transform
        with:
          working-directory: ${{ github.workspace }}/repo-contents
          content-directory: ${{ inputs.content-dir }}
      - uses: actions/upload-artifact@v3
        with:
          name: repo-contents-transformed
          path: repo-contents
          retention-days: 1

  load:
    needs: transform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: etl-actions
          path: actions
      - uses: actions/download-artifact@v3
        with:
          name: repo-contents-transformed
          path: repo-contents
      - name: Run Transform Action
        uses: ./actions/load
        with:
          working-directory: ${{ github.workspace }}/repo-contents
          content-directory: ${{ inputs.content-dir }}
