name: ETL
run-name: "ETL, repo: ${{ inputs.repository }}"

on:
  workflow_dispatch:
    inputs:
      repository:
        type: string
        description: The directory to run the ETL on. Like 'hashicorp/waypoint'
        required: false
      content-dir:
        type: string
        default: "content"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "=== SETUP ==="
      - uses: actions/checkout@v3
      # Make actions available to subsequent jobs
      - uses: actions/upload-artifact@v3
        with:
          name: etl-actions
          path: actions/

  extract:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "=== EXTRACT ==="
      - name: Download Actions
        uses: actions/download-artifact@v3
        with:
          name: etl-actions
      - name: Run Extract Action
        uses: ./actions/extract
        with:
          milliseconds: 2000

  transform:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "=== TRANSFORM ==="

  load:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "=== LOAD ==="
